#!/usr/bin/env bash
source config/config.sh

docker-compose -f ${FILE} run -T --name example_project_phpstan --no-deps \
                php sh -c "vendor/bin/phpstan analyse -c phpstan.neon -l 0 backend common frontend console"

docker rm -f example_project_phpstan > /dev/null
